name: Deploy Production
on:
  push:
    branches: ["prod"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      VITE_PUBLIC_APIKEY: ${{ vars.PROD_VITE_PUBLIC_APIKEY }}
      VITE_PUBLIC_AUTHDOMAIN: ${{ vars.PROD_VITE_PUBLIC_AUTHDOMAIN }}
      VITE_PUBLIC_PROJECTID: ${{ vars.PROD_VITE_PUBLIC_PROJECTID }}
      VITE_PUBLIC_STORAGEBUCKET: ${{ vars.PROD_VITE_PUBLIC_STORAGEBUCKET }}
      VITE_PUBLIC_MESSAGINGSENDERID: ${{ vars.PROD_VITE_PUBLIC_MESSAGINGSENDERID }}
      VITE_PUBLIC_APPID: ${{ vars.PROD_VITE_PUBLIC_APPID }}
      VITE_PUBLIC_MEASUREMENTID: ${{ vars.PROD_VITE_PUBLIC_MEASUREMENTID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install
        run: npm ci
        working-directory: ./

      - name: Build
        run: npm run build
        working-directory: ./

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.28.0
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.PROD_FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: jsw-prod
