name: Deploy Firebase Hosting (Prod)

on:
  push:
    branches:
      - prod # Trigger prod deployment on push/merge to prod branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Validate Environment Variables
        run: |
          echo "Checking environment variable lengths:"
          echo "VITE_FIREBASE_API_KEY length: ${#VITE_FIREBASE_API_KEY}"
          echo "VITE_FIREBASE_AUTH_DOMAIN length: ${#VITE_FIREBASE_AUTH_DOMAIN}"
          echo "VITE_FIREBASE_PROJECT_ID length: ${#VITE_FIREBASE_PROJECT_ID}"
          echo "VITE_FIREBASE_STORAGE_BUCKET length: ${#VITE_FIREBASE_STORAGE_BUCKET}"
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID length: ${#VITE_FIREBASE_MESSAGING_SENDER_ID}"
          echo "VITE_FIREBASE_APP_ID length: ${#VITE_FIREBASE_APP_ID}"
          echo "VITE_FIREBASE_MEASUREMENT_ID length: ${#VITE_FIREBASE_MEASUREMENT_ID}"
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}

      - name: Build Project
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: |
          echo "Environment variables present:"
          env | grep VITE_ || true
          echo "\nBuilding project:"
          npm run build
          echo "\nChecking build output:"
          ls -la dist/

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-prod
          path: dist

  deploy:
    name: Deploy (Production)
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      # url: <Your Prod Site URL> # Optional: Add prod site URL

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-prod
          path: dist

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (Production)
        id: deploy_firebase_prod
        run: |
          # Deploy Firestore Rules
          firebase deploy --only firestore:rules --project static-website-template-ee8ac --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"
          
          # Deploy Hosting to live channel
          firebase hosting:deploy --project static-website-template-ee8ac --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"

      - name: Deployment URL
        if: steps.deploy_firebase_prod.outputs.details_url
        run: echo "Deployed PROD to ${{ steps.deploy_firebase_prod.outputs.details_url }}"
