name: Deploy Firebase Hosting (Prod)

on:
  push:
    branches:
      - prod # Trigger prod deployment on push/merge to prod branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: npm run build

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-prod
          path: dist

  deploy:
    name: Deploy (Production)
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      # url: <Your Prod Site URL> # Optional: Add prod site URL

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-prod
          path: dist

      - name: Deploy to Firebase Hosting (Production)
        id: deploy_firebase_prod
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STATIC_WEBSITE_TEMPLATE_EE8AC }}"
          projectId: "static-website-template-ee8ac"

      - name: Deployment URL
        if: steps.deploy_firebase_prod.outputs.details_url
        run: echo "Deployed PROD to ${{ steps.deploy_firebase_prod.outputs.details_url }}"
